# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "manager" do  |manager|
    manager.vm.box = "bento/ubuntu-20.04"
    manager.vm.hostname = "manager.local.io"
    manager.vm.network "private_network", ip: "192.168.56.2"
    manager.vm.synced_folder "notebooks", "/notebooks",
      owner: "vagrant", group: "vagrant"

    manager.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

end
