# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.hostname = "manager.local.io"
    node1.vm.network "private_network", ip: "192.168.56.2"
    node1.vm.provision "shell", path: "deployLxd.sh"
  end

  #config.vm.define "node2" do |node2|
  #  node1.vm.box = "bento/ubuntu-20.04"
  #  node1.vm.hostname = "client.local.io"
  #  node1.vm.network "private_network", ip: "192.168.56.3"
  #end 
end
