# -*- mode: ruby -*-
# vi: set ft=ruby :

$import_keys = <<-KEYIMPORT
cat /tmp/id_rsa.pub  >> /home/vagrant/.ssh/authorized_keys
KEYIMPORT

$install_ansible = <<-ANSIBLE
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible -y
sudo apt install ansible -y
ANSIBLE

$deploy_sshpass = <<-SSHPASS
sudo apt install sshpass -y
SSHPASS

$install_keys = <<-KEYSPERMISSIONS
chmod 600 /home/vagrant/.ssh/id_rsa
chmod 600 /home/vagrant/.ssh/id_rsa.pub
sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" vagrant@192.168.56.3 
sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" vagrant@192.168.56.4 
KEYSPERMISSIONS

$edit_ansible = <<-ANSIBLECONFIG
cat << EOF >> /etc/ansible/ansible.cfg
[defaults]
host_key_checking = no
EOF
ANSIBLECONFIG

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.hostname = "node1.local.io"
    node1.vm.network "private_network", ip: "192.168.56.3"
    #node1.vm.provision "file", source: "./llaves/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    #node1.vm.provision "shell", inline: $import_keys, privileged: false
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/ubuntu-20.04"
    node2.vm.hostname = "node2.local.io"
    node2.vm.network "private_network", ip: "192.168.56.4"
    #node2.vm.provision "file", source: "./llaves/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    #node2.vm.provision "shell", inline: $import_keys, privileged: false
  end

  config.vm.define "manager" do |manager|
    manager.vm.box = "bento/ubuntu-20.04"
    manager.vm.hostname = "manager.local.io"
    manager.vm.network "private_network", ip: "192.168.56.2"
    manager.vm.provision "file", source: "./llaves/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
    manager.vm.provision "file", source: "./llaves/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    manager.vm.provision "file", source: "./llaves/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    manager.vm.provision "shell", inline: $deploy_sshpass
    manager.vm.provision "shell", inline: $install_ansible
    manager.vm.provision "shell", inline: $import_keys, privileged: false
    manager.vm.provision "shell", inline: $install_keys, privileged: false
    manager.vm.provision "shell", inline: $edit_ansible

    manager.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "master-playbook.yml"
      ansible.limit = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "inventory"
    end
  end

end
