# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  
  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.hostname = "manager.local.io"
    node1.vm.network "private_network", ip: "192.168.56.2"
    #node1.vm.network "forwarded_port", guest: 8888, host: 8888
    node1.vm.synced_folder "src/", "/notebooks"
        owner: "vagrant", group: "vagrant"
    node1.vm.provision "shell", path: "deployJupyter.sh"

  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/ubuntu-20.04"
    node2.vm.hostname = "client.local.io"
    node2.vm.network "private_network", ip: "192.168.56.3"
    node2.vm.provision "shell", path: "deployClient.sh"
  end

end
