---
- hosts: manager

  tasks:
    - name: init lxd
      become: yes
      become_user: vagrant
      command: lxd init --auto

    - name: create a container with lxd
      community.general.lxd_container:
        name: webserver
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/focal/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
        target: manager

    - name: install python in container
      delegate_to: webserver
      ansible.builtin.raw: apt install -y python