---
- hosts: all
  
  tasks:
    - name: update cache
      become: yes
      become_user: root
      apt:
        update_cache: yes

    - name: install pip
      become: yes
      become_user: root
      apt: 
        name: python3-pip
        state: latest

    - name: upgrade pip
      pip: 
        name: pip
        executable: pip3
        state: latest
    
    - name: install jupyter notebooks
      pip:
        name: notebook
        executable: pip3
        state: latest

    - name: update version of markupsafe
      pip:
        name: markupsafe==2.0.1
        executable: pip3
        state: present
      
    - name: run jupyter notebooks
      become: yes
      become_user: vagrant
      shell: "nohup /home/vagrant/.local/bin/jupyter notebook --no-browser --ip=0.0.0.0 --notebook-dir='/notebooks' &"
      async: 10

    - name: display run notebooks
      become: yes
      become_user: vagrant
      command: "/home/vagrant/.local/bin/jupyter notebook list"
      register: out

    
    
    

    - debug: var=out.stdout_lines
