# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_puppet = <<-PUPPET
sudo apt update -y
sudo apt install -y puppet
PUPPET

$install_ansible = <<-ANSIBLE
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible -y
sudo apt install ansible -y
ANSIBLE

$install_galaxy = <<-GALAXY
ansible-galaxy collection install community.general
GALAXY

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "manager" do  |manager|
    manager.vm.box = "bento/ubuntu-20.04"
    manager.vm.hostname = "manager.local.io"
    manager.vm.network "private_network", ip: "192.168.56.2"
    manager.vm.synced_folder "ansible/notebooks", "/notebooks",
      owner: "vagrant", group: "vagrant"
    manager.vm.provision "shell", inline: $install_puppet
    manager.vm.provision "shell", inline: $install_ansible
    manager.vm.provision "shell", inline: $install_galaxy, privileged: false
    manager.vm.provision "shell", path: "script.sh"

    manager.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "puppet/modules"
    end

    manager.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/master-playbook.yml"
    end
  end

end
