# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_ansible = <<-ANSIBLE
sudo apt update -y
sudo apt install software-properties-common -y
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible
ansible-galaxy collection install community.general
ANSIBLE

Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.hostname = "manager.local.io"
    node1.vm.network "private_network", ip: "192.168.56.2"
    #node1.vm.synced_folder "notebooks/", "/notebooks"
    node1.vm.provision "shell", inline: $install_ansible
    node1.vm.provision "ansible" do |ansible| 
      ansible.playbook="containers-playbook.yml" 
    end


  end
end
