# -*- mode: ruby -*-
# vi: set ft=ruby :

$deploy_sshpass = <<-SSHPASS
sudo apt install sshpass -y
SSHPASS

$install_keys = <<-KEYSPERMISSIONS
ssh-keygen -t rsa -b 4096 -f /home/vagrant/.ssh/id_rsa -q -P ""
chmod 600 /home/vagrant/.ssh/id_rsa
chmod 600 /home/vagrant/.ssh/id_rsa.pub
sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" vagrant@192.168.56.2 
sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" vagrant@192.168.56.3 
sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/id_rsa -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" vagrant@192.168.56.4 
KEYSPERMISSIONS

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "bento/ubuntu-20.04"
    node1.vm.hostname = "node1.local.io"
    node1.vm.network "private_network", ip: "192.168.56.3"
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "bento/ubuntu-20.04"
    node2.vm.hostname = "node2.local.io"
    node2.vm.network "private_network", ip: "192.168.56.4"
  end

  config.vm.define "manager" do |manager|
    manager.vm.box = "bento/ubuntu-20.04"
    manager.vm.hostname = "manager.local.io"
    manager.vm.network "private_network", ip: "192.168.56.2"

    manager.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.install        = true
      ansible.verbose        = true
      ansible.limit          = "all" # or only "nodes" group, etc.
      ansible.inventory_path = "ansible/inventory"
    end
  end

end
